# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eeva_designer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 475)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/NERLogoTransparent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mainHorizontalLayout = QtGui.QHBoxLayout()
        self.mainHorizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.mainHorizontalLayout.setContentsMargins(2, -1, 4, -1)
        self.mainHorizontalLayout.setSpacing(4)
        self.mainHorizontalLayout.setObjectName(_fromUtf8("mainHorizontalLayout"))
        self.verticalFrame_3 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame_3.sizePolicy().hasHeightForWidth())
        self.verticalFrame_3.setSizePolicy(sizePolicy)
        self.verticalFrame_3.setObjectName(_fromUtf8("verticalFrame_3"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalFrame_4 = QtGui.QFrame(self.verticalFrame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_4.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_4.setSizePolicy(sizePolicy)
        self.horizontalFrame_4.setObjectName(_fromUtf8("horizontalFrame_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.horizontalFrame_4)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(2, -1, 2, -1)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_19 = QtGui.QLabel(self.horizontalFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.connectButton = QtGui.QPushButton(self.horizontalFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 0))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.refreshPortsButton = QtGui.QPushButton(self.horizontalFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshPortsButton.sizePolicy().hasHeightForWidth())
        self.refreshPortsButton.setSizePolicy(sizePolicy)
        self.refreshPortsButton.setMinimumSize(QtCore.QSize(0, 0))
        self.refreshPortsButton.setObjectName(_fromUtf8("refreshPortsButton"))
        self.horizontalLayout_2.addWidget(self.refreshPortsButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 2, 3)
        self.portsComboBox = QtGui.QComboBox(self.horizontalFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portsComboBox.sizePolicy().hasHeightForWidth())
        self.portsComboBox.setSizePolicy(sizePolicy)
        self.portsComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.portsComboBox.setMaxVisibleItems(20)
        self.portsComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.portsComboBox.setObjectName(_fromUtf8("portsComboBox"))
        self.gridLayout_4.addWidget(self.portsComboBox, 0, 2, 1, 1)
        self.verticalLayout_17.addWidget(self.horizontalFrame_4)
        self.messageCenterLabel = QtGui.QLabel(self.verticalFrame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageCenterLabel.sizePolicy().hasHeightForWidth())
        self.messageCenterLabel.setSizePolicy(sizePolicy)
        self.messageCenterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageCenterLabel.setObjectName(_fromUtf8("messageCenterLabel"))
        self.verticalLayout_17.addWidget(self.messageCenterLabel, QtCore.Qt.AlignHCenter)
        self.messageCenterTextEdit = QtGui.QTextEdit(self.verticalFrame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageCenterTextEdit.sizePolicy().hasHeightForWidth())
        self.messageCenterTextEdit.setSizePolicy(sizePolicy)
        self.messageCenterTextEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.messageCenterTextEdit.setReadOnly(True)
        self.messageCenterTextEdit.setObjectName(_fromUtf8("messageCenterTextEdit"))
        self.verticalLayout_17.addWidget(self.messageCenterTextEdit)
        self.connectionGroupBox = QtGui.QGroupBox(self.verticalFrame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionGroupBox.sizePolicy().hasHeightForWidth())
        self.connectionGroupBox.setSizePolicy(sizePolicy)
        self.connectionGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionGroupBox.setObjectName(_fromUtf8("connectionGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.connectionGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_91 = QtGui.QLabel(self.connectionGroupBox)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_7.addWidget(self.label_91, 0, 0, 1, 1)
        self.txPacketsLineEdit = QtGui.QLineEdit(self.connectionGroupBox)
        self.txPacketsLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.txPacketsLineEdit.setReadOnly(True)
        self.txPacketsLineEdit.setObjectName(_fromUtf8("txPacketsLineEdit"))
        self.gridLayout_7.addWidget(self.txPacketsLineEdit, 1, 1, 1, 1)
        self.label_92 = QtGui.QLabel(self.connectionGroupBox)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_7.addWidget(self.label_92, 1, 2, 1, 1)
        self.txBPSLineEdit = QtGui.QLineEdit(self.connectionGroupBox)
        self.txBPSLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.txBPSLineEdit.setReadOnly(True)
        self.txBPSLineEdit.setObjectName(_fromUtf8("txBPSLineEdit"))
        self.gridLayout_7.addWidget(self.txBPSLineEdit, 1, 3, 1, 1)
        self.rxBPSLineEdit = QtGui.QLineEdit(self.connectionGroupBox)
        self.rxBPSLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rxBPSLineEdit.setReadOnly(True)
        self.rxBPSLineEdit.setObjectName(_fromUtf8("rxBPSLineEdit"))
        self.gridLayout_7.addWidget(self.rxBPSLineEdit, 0, 3, 1, 1)
        self.label_93 = QtGui.QLabel(self.connectionGroupBox)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_7.addWidget(self.label_93, 0, 2, 1, 1)
        self.label_94 = QtGui.QLabel(self.connectionGroupBox)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_7.addWidget(self.label_94, 1, 0, 1, 1)
        self.rxPacketsLineEdit = QtGui.QLineEdit(self.connectionGroupBox)
        self.rxPacketsLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rxPacketsLineEdit.setReadOnly(True)
        self.rxPacketsLineEdit.setObjectName(_fromUtf8("rxPacketsLineEdit"))
        self.gridLayout_7.addWidget(self.rxPacketsLineEdit, 0, 1, 1, 1)
        self.label_95 = QtGui.QLabel(self.connectionGroupBox)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_7.addWidget(self.label_95, 2, 0, 1, 1)
        self.badCRCLineEdit = QtGui.QLineEdit(self.connectionGroupBox)
        self.badCRCLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.badCRCLineEdit.setReadOnly(True)
        self.badCRCLineEdit.setObjectName(_fromUtf8("badCRCLineEdit"))
        self.gridLayout_7.addWidget(self.badCRCLineEdit, 2, 1, 1, 1)
        self.label_96 = QtGui.QLabel(self.connectionGroupBox)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_7.addWidget(self.label_96, 2, 2, 1, 1)
        self.droppedLineEdit = QtGui.QLineEdit(self.connectionGroupBox)
        self.droppedLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.droppedLineEdit.setReadOnly(True)
        self.droppedLineEdit.setObjectName(_fromUtf8("droppedLineEdit"))
        self.gridLayout_7.addWidget(self.droppedLineEdit, 2, 3, 1, 1)
        self.verticalLayout_17.addWidget(self.connectionGroupBox)
        self.mainHorizontalLayout.addWidget(self.verticalFrame_3)
        self.verticalLayout2 = QtGui.QVBoxLayout()
        self.verticalLayout2.setObjectName(_fromUtf8("verticalLayout2"))
        self.modeGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeGroupBox.sizePolicy().hasHeightForWidth())
        self.modeGroupBox.setSizePolicy(sizePolicy)
        self.modeGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.modeGroupBox.setFlat(False)
        self.modeGroupBox.setCheckable(False)
        self.modeGroupBox.setObjectName(_fromUtf8("modeGroupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.modeGroupBox)
        self.verticalLayout_7.setContentsMargins(17, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.balanceRadioButton = QtGui.QRadioButton(self.modeGroupBox)
        self.balanceRadioButton.setObjectName(_fromUtf8("balanceRadioButton"))
        self.verticalLayout_7.addWidget(self.balanceRadioButton)
        self.horizontalRadioButton = QtGui.QRadioButton(self.modeGroupBox)
        self.horizontalRadioButton.setObjectName(_fromUtf8("horizontalRadioButton"))
        self.verticalLayout_7.addWidget(self.horizontalRadioButton)
        self.followLineRadioButton = QtGui.QRadioButton(self.modeGroupBox)
        self.followLineRadioButton.setObjectName(_fromUtf8("followLineRadioButton"))
        self.verticalLayout_7.addWidget(self.followLineRadioButton)
        self.experimentRadioButton = QtGui.QRadioButton(self.modeGroupBox)
        self.experimentRadioButton.setObjectName(_fromUtf8("experimentRadioButton"))
        self.verticalLayout_7.addWidget(self.experimentRadioButton)
        self.customRadioButton = QtGui.QRadioButton(self.modeGroupBox)
        self.customRadioButton.setObjectName(_fromUtf8("customRadioButton"))
        self.verticalLayout_7.addWidget(self.customRadioButton)
        self.verticalLayout2.addWidget(self.modeGroupBox)
        self.experimentComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experimentComboBox.sizePolicy().hasHeightForWidth())
        self.experimentComboBox.setSizePolicy(sizePolicy)
        self.experimentComboBox.setObjectName(_fromUtf8("experimentComboBox"))
        self.verticalLayout2.addWidget(self.experimentComboBox)
        self.mainButtonsFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainButtonsFrame.sizePolicy().hasHeightForWidth())
        self.mainButtonsFrame.setSizePolicy(sizePolicy)
        self.mainButtonsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainButtonsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.mainButtonsFrame.setObjectName(_fromUtf8("mainButtonsFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mainButtonsFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.startButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayout.addWidget(self.startButton)
        self.collectDataButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.collectDataButton.setObjectName(_fromUtf8("collectDataButton"))
        self.verticalLayout.addWidget(self.collectDataButton)
        self.startAndCollectButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.startAndCollectButton.setObjectName(_fromUtf8("startAndCollectButton"))
        self.verticalLayout.addWidget(self.startAndCollectButton)
        self.stopButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.verticalLayout.addWidget(self.stopButton)
        self.resetStateButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.resetStateButton.setObjectName(_fromUtf8("resetStateButton"))
        self.verticalLayout.addWidget(self.resetStateButton)
        self.enableDrivingButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.enableDrivingButton.setObjectName(_fromUtf8("enableDrivingButton"))
        self.verticalLayout.addWidget(self.enableDrivingButton)
        self.openOutputDirectoryButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.openOutputDirectoryButton.setObjectName(_fromUtf8("openOutputDirectoryButton"))
        self.verticalLayout.addWidget(self.openOutputDirectoryButton)
        self.changeOutputDirectoryButton = QtGui.QPushButton(self.mainButtonsFrame)
        self.changeOutputDirectoryButton.setObjectName(_fromUtf8("changeOutputDirectoryButton"))
        self.verticalLayout.addWidget(self.changeOutputDirectoryButton)
        self.verticalLayout2.addWidget(self.mainButtonsFrame)
        self.mainHorizontalLayout.addLayout(self.verticalLayout2)
        self.verticalLayout3 = QtGui.QVBoxLayout()
        self.verticalLayout3.setObjectName(_fromUtf8("verticalLayout3"))
        self.dataCollectionGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.dataCollectionGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.dataCollectionGroupBox.setObjectName(_fromUtf8("dataCollectionGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dataCollectionGroupBox)
        self.verticalLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame = QtGui.QFrame(self.dataCollectionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.durationLineEdit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationLineEdit.sizePolicy().hasHeightForWidth())
        self.durationLineEdit.setSizePolicy(sizePolicy)
        self.durationLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.durationLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.durationLineEdit.setReadOnly(True)
        self.durationLineEdit.setObjectName(_fromUtf8("durationLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.durationLineEdit)
        self.sampleCountTextEdit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleCountTextEdit.sizePolicy().hasHeightForWidth())
        self.sampleCountTextEdit.setSizePolicy(sizePolicy)
        self.sampleCountTextEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.sampleCountTextEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleCountTextEdit.setObjectName(_fromUtf8("sampleCountTextEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sampleCountTextEdit)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sampleRateTextEdit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRateTextEdit.sizePolicy().hasHeightForWidth())
        self.sampleRateTextEdit.setSizePolicy(sizePolicy)
        self.sampleRateTextEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.sampleRateTextEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleRateTextEdit.setObjectName(_fromUtf8("sampleRateTextEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sampleRateTextEdit)
        self.verticalLayout_4.addWidget(self.frame)
        self.label_2 = QtGui.QLabel(self.dataCollectionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.dataFileNameLineEdit = QtGui.QLineEdit(self.dataCollectionGroupBox)
        self.dataFileNameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dataFileNameLineEdit.setObjectName(_fromUtf8("dataFileNameLineEdit"))
        self.verticalLayout_4.addWidget(self.dataFileNameLineEdit)
        self.frame_4 = QtGui.QFrame(self.dataCollectionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.generateFileNameCheckBox = QtGui.QCheckBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateFileNameCheckBox.sizePolicy().hasHeightForWidth())
        self.generateFileNameCheckBox.setSizePolicy(sizePolicy)
        self.generateFileNameCheckBox.setObjectName(_fromUtf8("generateFileNameCheckBox"))
        self.horizontalLayout.addWidget(self.generateFileNameCheckBox)
        spacerItem1 = QtGui.QSpacerItem(4, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout3.addWidget(self.dataCollectionGroupBox)
        self.controllerGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.controllerGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.controllerGroupBox.setObjectName(_fromUtf8("controllerGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.controllerGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.controlComboBox = QtGui.QComboBox(self.controllerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlComboBox.sizePolicy().hasHeightForWidth())
        self.controlComboBox.setSizePolicy(sizePolicy)
        self.controlComboBox.setObjectName(_fromUtf8("controlComboBox"))
        self.verticalLayout_6.addWidget(self.controlComboBox)
        self.frame_3 = QtGui.QFrame(self.controllerGroupBox)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_2.setContentsMargins(0, 8, 0, 0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_10)
        self.proportionalLineEdit = QtGui.QLineEdit(self.frame_3)
        self.proportionalLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.proportionalLineEdit.setObjectName(_fromUtf8("proportionalLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.proportionalLineEdit)
        self.integralLineEdit = QtGui.QLineEdit(self.frame_3)
        self.integralLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.integralLineEdit.setObjectName(_fromUtf8("integralLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.integralLineEdit)
        self.derivativeLineEdit = QtGui.QLineEdit(self.frame_3)
        self.derivativeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.derivativeLineEdit.setObjectName(_fromUtf8("derivativeLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.derivativeLineEdit)
        self.satLimitLineEdit = QtGui.QLineEdit(self.frame_3)
        self.satLimitLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.satLimitLineEdit.setObjectName(_fromUtf8("satLimitLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.satLimitLineEdit)
        self.intSatLimitLineEdit = QtGui.QLineEdit(self.frame_3)
        self.intSatLimitLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.intSatLimitLineEdit.setObjectName(_fromUtf8("intSatLimitLineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.intSatLimitLineEdit)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.verticalLayout3.addWidget(self.controllerGroupBox)
        self.mainHorizontalLayout.addLayout(self.verticalLayout3)
        self.experimentInputGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experimentInputGroupBox.sizePolicy().hasHeightForWidth())
        self.experimentInputGroupBox.setSizePolicy(sizePolicy)
        self.experimentInputGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.experimentInputGroupBox.setObjectName(_fromUtf8("experimentInputGroupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.experimentInputGroupBox)
        self.verticalLayout_9.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.manualGroupBox = QtGui.QGroupBox(self.experimentInputGroupBox)
        self.manualGroupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualGroupBox.sizePolicy().hasHeightForWidth())
        self.manualGroupBox.setSizePolicy(sizePolicy)
        self.manualGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.manualGroupBox.setCheckable(True)
        self.manualGroupBox.setChecked(False)
        self.manualGroupBox.setObjectName(_fromUtf8("manualGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.manualGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.manualIncrementLineEdit = QtGui.QLineEdit(self.manualGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualIncrementLineEdit.sizePolicy().hasHeightForWidth())
        self.manualIncrementLineEdit.setSizePolicy(sizePolicy)
        self.manualIncrementLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.manualIncrementLineEdit.setObjectName(_fromUtf8("manualIncrementLineEdit"))
        self.gridLayout_3.addWidget(self.manualIncrementLineEdit, 3, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.manualGroupBox)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)
        self.manualCommandLineEdit = QtGui.QLineEdit(self.manualGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualCommandLineEdit.sizePolicy().hasHeightForWidth())
        self.manualCommandLineEdit.setSizePolicy(sizePolicy)
        self.manualCommandLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.manualCommandLineEdit.setObjectName(_fromUtf8("manualCommandLineEdit"))
        self.gridLayout_3.addWidget(self.manualCommandLineEdit, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.manualGroupBox)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.manualGroupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.manualCommandIncreaseButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualCommandIncreaseButton.sizePolicy().hasHeightForWidth())
        self.manualCommandIncreaseButton.setSizePolicy(sizePolicy)
        self.manualCommandIncreaseButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.manualCommandIncreaseButton.setObjectName(_fromUtf8("manualCommandIncreaseButton"))
        self.verticalLayout_2.addWidget(self.manualCommandIncreaseButton)
        self.manualCommandDecreaseButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualCommandDecreaseButton.sizePolicy().hasHeightForWidth())
        self.manualCommandDecreaseButton.setSizePolicy(sizePolicy)
        self.manualCommandDecreaseButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.manualCommandDecreaseButton.setObjectName(_fromUtf8("manualCommandDecreaseButton"))
        self.verticalLayout_2.addWidget(self.manualCommandDecreaseButton)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 4, 1)
        self.verticalLayout_9.addWidget(self.manualGroupBox)
        self.autoWaveGroupBox = QtGui.QGroupBox(self.experimentInputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoWaveGroupBox.sizePolicy().hasHeightForWidth())
        self.autoWaveGroupBox.setSizePolicy(sizePolicy)
        self.autoWaveGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.autoWaveGroupBox.setCheckable(True)
        self.autoWaveGroupBox.setObjectName(_fromUtf8("autoWaveGroupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.autoWaveGroupBox)
        self.verticalLayout_8.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.sineRadioButton = QtGui.QRadioButton(self.autoWaveGroupBox)
        self.sineRadioButton.setObjectName(_fromUtf8("sineRadioButton"))
        self.verticalLayout_8.addWidget(self.sineRadioButton)
        self.squareRadioButton = QtGui.QRadioButton(self.autoWaveGroupBox)
        self.squareRadioButton.setObjectName(_fromUtf8("squareRadioButton"))
        self.verticalLayout_8.addWidget(self.squareRadioButton)
        self.triangleRadioButton = QtGui.QRadioButton(self.autoWaveGroupBox)
        self.triangleRadioButton.setObjectName(_fromUtf8("triangleRadioButton"))
        self.verticalLayout_8.addWidget(self.triangleRadioButton)
        self.trapezoidRadioButton = QtGui.QRadioButton(self.autoWaveGroupBox)
        self.trapezoidRadioButton.setObjectName(_fromUtf8("trapezoidRadioButton"))
        self.verticalLayout_8.addWidget(self.trapezoidRadioButton)
        self.frame_6 = QtGui.QFrame(self.autoWaveGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_6)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.waveMagnitudeLineEdit = QtGui.QLineEdit(self.frame_6)
        self.waveMagnitudeLineEdit.setText(_fromUtf8(""))
        self.waveMagnitudeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.waveMagnitudeLineEdit.setObjectName(_fromUtf8("waveMagnitudeLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.waveMagnitudeLineEdit)
        self.label = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_50 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_50)
        self.waveOffsetLineEdit = QtGui.QLineEdit(self.frame_6)
        self.waveOffsetLineEdit.setText(_fromUtf8(""))
        self.waveOffsetLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.waveOffsetLineEdit.setObjectName(_fromUtf8("waveOffsetLineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.waveOffsetLineEdit)
        self.label_26 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_26)
        self.waveFrequencyLineEdit = QtGui.QLineEdit(self.frame_6)
        self.waveFrequencyLineEdit.setText(_fromUtf8(""))
        self.waveFrequencyLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.waveFrequencyLineEdit.setObjectName(_fromUtf8("waveFrequencyLineEdit"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.waveFrequencyLineEdit)
        self.label_51 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_51)
        self.waveDurationLineEdit = QtGui.QLineEdit(self.frame_6)
        self.waveDurationLineEdit.setText(_fromUtf8(""))
        self.waveDurationLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.waveDurationLineEdit.setObjectName(_fromUtf8("waveDurationLineEdit"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.waveDurationLineEdit)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.autoWaveGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.runWaveContinuousCheckBox = QtGui.QCheckBox(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runWaveContinuousCheckBox.sizePolicy().hasHeightForWidth())
        self.runWaveContinuousCheckBox.setSizePolicy(sizePolicy)
        self.runWaveContinuousCheckBox.setObjectName(_fromUtf8("runWaveContinuousCheckBox"))
        self.horizontalLayout_4.addWidget(self.runWaveContinuousCheckBox)
        spacerItem4 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_5 = QtGui.QFrame(self.autoWaveGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8.addWidget(self.frame_5)
        self.verticalLayout_9.addWidget(self.autoWaveGroupBox)
        self.mainHorizontalLayout.addWidget(self.experimentInputGroupBox)
        self.statusGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.statusGroupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusGroupBox.sizePolicy().hasHeightForWidth())
        self.statusGroupBox.setSizePolicy(sizePolicy)
        self.statusGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.statusGroupBox.setObjectName(_fromUtf8("statusGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.statusGroupBox)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_35 = QtGui.QLabel(self.statusGroupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 14, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.statusGroupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 3, 1, 1)
        self.pitchLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.pitchLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitchLineEdit.sizePolicy().hasHeightForWidth())
        self.pitchLineEdit.setSizePolicy(sizePolicy)
        self.pitchLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pitchLineEdit.setReadOnly(True)
        self.pitchLineEdit.setObjectName(_fromUtf8("pitchLineEdit"))
        self.gridLayout.addWidget(self.pitchLineEdit, 3, 1, 1, 2)
        self.label_17 = QtGui.QLabel(self.statusGroupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 4, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.statusGroupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.statusGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.statusGroupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.statusGroupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.statusGroupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.statusGroupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.rollLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rollLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollLineEdit.sizePolicy().hasHeightForWidth())
        self.rollLineEdit.setSizePolicy(sizePolicy)
        self.rollLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rollLineEdit.setReadOnly(True)
        self.rollLineEdit.setObjectName(_fromUtf8("rollLineEdit"))
        self.gridLayout.addWidget(self.rollLineEdit, 2, 1, 1, 2)
        self.label_28 = QtGui.QLabel(self.statusGroupBox)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 10, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.statusGroupBox)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 10, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.statusGroupBox)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 12, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.statusGroupBox)
        self.label_30.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 7, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.statusGroupBox)
        self.label_29.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 7, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.statusGroupBox)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 11, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.statusGroupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 8, 3, 1, 1)
        self.label_31 = QtGui.QLabel(self.statusGroupBox)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 8, 0, 1, 1)
        self.yawLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.yawLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yawLineEdit.sizePolicy().hasHeightForWidth())
        self.yawLineEdit.setSizePolicy(sizePolicy)
        self.yawLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yawLineEdit.setReadOnly(True)
        self.yawLineEdit.setObjectName(_fromUtf8("yawLineEdit"))
        self.gridLayout.addWidget(self.yawLineEdit, 4, 1, 1, 2)
        self.label_42 = QtGui.QLabel(self.statusGroupBox)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 12, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.statusGroupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 14, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self.statusGroupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 13, 3, 1, 1)
        self.label_37 = QtGui.QLabel(self.statusGroupBox)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 13, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.statusGroupBox)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 11, 0, 1, 1)
        self.batteryLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.batteryLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryLineEdit.sizePolicy().hasHeightForWidth())
        self.batteryLineEdit.setSizePolicy(sizePolicy)
        self.batteryLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.batteryLineEdit.setReadOnly(True)
        self.batteryLineEdit.setObjectName(_fromUtf8("batteryLineEdit"))
        self.gridLayout.addWidget(self.batteryLineEdit, 0, 1, 1, 2)
        self.modeLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.modeLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLineEdit.sizePolicy().hasHeightForWidth())
        self.modeLineEdit.setSizePolicy(sizePolicy)
        self.modeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.modeLineEdit.setReadOnly(True)
        self.modeLineEdit.setObjectName(_fromUtf8("modeLineEdit"))
        self.gridLayout.addWidget(self.modeLineEdit, 5, 1, 1, 2)
        self.label_25 = QtGui.QLabel(self.statusGroupBox)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.statusGroupBox)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 5, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 15, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem6, 6, 2, 1, 1)
        self.lAPLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.lAPLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAPLineEdit.sizePolicy().hasHeightForWidth())
        self.lAPLineEdit.setSizePolicy(sizePolicy)
        self.lAPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lAPLineEdit.setReadOnly(True)
        self.lAPLineEdit.setObjectName(_fromUtf8("lAPLineEdit"))
        self.gridLayout.addWidget(self.lAPLineEdit, 8, 1, 1, 1)
        self.rAPLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rAPLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rAPLineEdit.sizePolicy().hasHeightForWidth())
        self.rAPLineEdit.setSizePolicy(sizePolicy)
        self.rAPLineEdit.setText(_fromUtf8(""))
        self.rAPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rAPLineEdit.setReadOnly(True)
        self.rAPLineEdit.setObjectName(_fromUtf8("rAPLineEdit"))
        self.gridLayout.addWidget(self.rAPLineEdit, 8, 2, 1, 1)
        self.lAVLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.lAVLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAVLineEdit.sizePolicy().hasHeightForWidth())
        self.lAVLineEdit.setSizePolicy(sizePolicy)
        self.lAVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lAVLineEdit.setReadOnly(True)
        self.lAVLineEdit.setObjectName(_fromUtf8("lAVLineEdit"))
        self.gridLayout.addWidget(self.lAVLineEdit, 10, 1, 1, 1)
        self.rAVLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rAVLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rAVLineEdit.sizePolicy().hasHeightForWidth())
        self.rAVLineEdit.setSizePolicy(sizePolicy)
        self.rAVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rAVLineEdit.setReadOnly(True)
        self.rAVLineEdit.setObjectName(_fromUtf8("rAVLineEdit"))
        self.gridLayout.addWidget(self.rAVLineEdit, 10, 2, 1, 1)
        self.lLPLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.lLPLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lLPLineEdit.sizePolicy().hasHeightForWidth())
        self.lLPLineEdit.setSizePolicy(sizePolicy)
        self.lLPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lLPLineEdit.setReadOnly(True)
        self.lLPLineEdit.setObjectName(_fromUtf8("lLPLineEdit"))
        self.gridLayout.addWidget(self.lLPLineEdit, 11, 1, 1, 1)
        self.rLPLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rLPLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rLPLineEdit.sizePolicy().hasHeightForWidth())
        self.rLPLineEdit.setSizePolicy(sizePolicy)
        self.rLPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rLPLineEdit.setReadOnly(True)
        self.rLPLineEdit.setObjectName(_fromUtf8("rLPLineEdit"))
        self.gridLayout.addWidget(self.rLPLineEdit, 11, 2, 1, 1)
        self.lLVLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.lLVLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lLVLineEdit.sizePolicy().hasHeightForWidth())
        self.lLVLineEdit.setSizePolicy(sizePolicy)
        self.lLVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lLVLineEdit.setReadOnly(True)
        self.lLVLineEdit.setObjectName(_fromUtf8("lLVLineEdit"))
        self.gridLayout.addWidget(self.lLVLineEdit, 12, 1, 1, 1)
        self.rLVLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rLVLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rLVLineEdit.sizePolicy().hasHeightForWidth())
        self.rLVLineEdit.setSizePolicy(sizePolicy)
        self.rLVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rLVLineEdit.setReadOnly(True)
        self.rLVLineEdit.setObjectName(_fromUtf8("rLVLineEdit"))
        self.gridLayout.addWidget(self.rLVLineEdit, 12, 2, 1, 1)
        self.lVLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.lVLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lVLineEdit.sizePolicy().hasHeightForWidth())
        self.lVLineEdit.setSizePolicy(sizePolicy)
        self.lVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lVLineEdit.setReadOnly(True)
        self.lVLineEdit.setObjectName(_fromUtf8("lVLineEdit"))
        self.gridLayout.addWidget(self.lVLineEdit, 13, 1, 1, 1)
        self.rVLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rVLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rVLineEdit.sizePolicy().hasHeightForWidth())
        self.rVLineEdit.setSizePolicy(sizePolicy)
        self.rVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rVLineEdit.setReadOnly(True)
        self.rVLineEdit.setObjectName(_fromUtf8("rVLineEdit"))
        self.gridLayout.addWidget(self.rVLineEdit, 13, 2, 1, 1)
        self.lPWMLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.lPWMLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lPWMLineEdit.sizePolicy().hasHeightForWidth())
        self.lPWMLineEdit.setSizePolicy(sizePolicy)
        self.lPWMLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lPWMLineEdit.setReadOnly(True)
        self.lPWMLineEdit.setObjectName(_fromUtf8("lPWMLineEdit"))
        self.gridLayout.addWidget(self.lPWMLineEdit, 14, 1, 1, 1)
        self.rPWMLineEdit = QtGui.QLineEdit(self.statusGroupBox)
        self.rPWMLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rPWMLineEdit.sizePolicy().hasHeightForWidth())
        self.rPWMLineEdit.setSizePolicy(sizePolicy)
        self.rPWMLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rPWMLineEdit.setReadOnly(True)
        self.rPWMLineEdit.setObjectName(_fromUtf8("rPWMLineEdit"))
        self.gridLayout.addWidget(self.rPWMLineEdit, 14, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 15, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem8, 6, 1, 1, 1)
        self.mainHorizontalLayout.addWidget(self.statusGroupBox)
        self.gridLayout_2.addLayout(self.mainHorizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange_Output_Directory = QtGui.QAction(MainWindow)
        self.actionChange_Output_Directory.setObjectName(_fromUtf8("actionChange_Output_Directory"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "EevaUI", None))
        self.label_19.setText(_translate("MainWindow", "Bluetooth Port:", None))
        self.connectButton.setText(_translate("MainWindow", "Connect to Eeva", None))
        self.refreshPortsButton.setText(_translate("MainWindow", "Refresh Ports", None))
        self.messageCenterLabel.setText(_translate("MainWindow", "Message Center", None))
        self.connectionGroupBox.setTitle(_translate("MainWindow", "Connection", None))
        self.label_91.setText(_translate("MainWindow", "Rx Packets", None))
        self.label_92.setText(_translate("MainWindow", "Tx BPS", None))
        self.label_93.setText(_translate("MainWindow", "Rx BPS", None))
        self.label_94.setText(_translate("MainWindow", "Tx Packets", None))
        self.label_95.setText(_translate("MainWindow", "Bad CRC", None))
        self.label_96.setText(_translate("MainWindow", "Dropped", None))
        self.modeGroupBox.setTitle(_translate("MainWindow", "Mode", None))
        self.balanceRadioButton.setText(_translate("MainWindow", "Balance", None))
        self.horizontalRadioButton.setText(_translate("MainWindow", "Horizontal", None))
        self.followLineRadioButton.setText(_translate("MainWindow", "Line Following", None))
        self.experimentRadioButton.setText(_translate("MainWindow", "Experiment", None))
        self.customRadioButton.setText(_translate("MainWindow", "Custom", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.collectDataButton.setText(_translate("MainWindow", "Collect Data", None))
        self.startAndCollectButton.setText(_translate("MainWindow", "Start + Collect Data", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.resetStateButton.setText(_translate("MainWindow", "Reset State", None))
        self.enableDrivingButton.setText(_translate("MainWindow", "Enable Driving", None))
        self.openOutputDirectoryButton.setText(_translate("MainWindow", "Open Directory", None))
        self.changeOutputDirectoryButton.setText(_translate("MainWindow", "Change Directory", None))
        self.dataCollectionGroupBox.setTitle(_translate("MainWindow", "Data Collection", None))
        self.label_3.setText(_translate("MainWindow", "Sample Rate (Hz)", None))
        self.label_5.setText(_translate("MainWindow", "Duration (sec)", None))
        self.label_4.setText(_translate("MainWindow", "Sample Count", None))
        self.label_2.setText(_translate("MainWindow", "Data File Name", None))
        self.generateFileNameCheckBox.setText(_translate("MainWindow", "Generate File Name", None))
        self.controllerGroupBox.setTitle(_translate("MainWindow", "Controller", None))
        self.label_6.setText(_translate("MainWindow", "Proportional", None))
        self.label_8.setText(_translate("MainWindow", "Integral", None))
        self.label_7.setText(_translate("MainWindow", "Derivative", None))
        self.label_9.setText(_translate("MainWindow", "Sat. Limit", None))
        self.label_10.setText(_translate("MainWindow", "I. Sat. Limit", None))
        self.experimentInputGroupBox.setTitle(_translate("MainWindow", "Experiment Input", None))
        self.manualGroupBox.setTitle(_translate("MainWindow", "Manual", None))
        self.label_23.setText(_translate("MainWindow", "Command", None))
        self.label_24.setText(_translate("MainWindow", "Increment", None))
        self.manualCommandIncreaseButton.setText(_translate("MainWindow", "+", None))
        self.manualCommandDecreaseButton.setText(_translate("MainWindow", "-", None))
        self.autoWaveGroupBox.setTitle(_translate("MainWindow", "Auto Wave", None))
        self.sineRadioButton.setText(_translate("MainWindow", "Sine", None))
        self.squareRadioButton.setText(_translate("MainWindow", "Square", None))
        self.triangleRadioButton.setText(_translate("MainWindow", "Triangle", None))
        self.trapezoidRadioButton.setText(_translate("MainWindow", "Trapezoidal", None))
        self.label.setText(_translate("MainWindow", "Magnitude", None))
        self.label_50.setText(_translate("MainWindow", "Offset", None))
        self.label_26.setText(_translate("MainWindow", "Freq (Hz)", None))
        self.label_51.setText(_translate("MainWindow", "Duration (s)", None))
        self.runWaveContinuousCheckBox.setText(_translate("MainWindow", "Run Continuous", None))
        self.statusGroupBox.setTitle(_translate("MainWindow", "Status", None))
        self.label_35.setText(_translate("MainWindow", "PWM", None))
        self.label_14.setText(_translate("MainWindow", "deg", None))
        self.label_17.setText(_translate("MainWindow", "deg", None))
        self.label_11.setText(_translate("MainWindow", "Battery", None))
        self.label_12.setText(_translate("MainWindow", "volts", None))
        self.label_13.setText(_translate("MainWindow", "Roll", None))
        self.label_16.setText(_translate("MainWindow", "deg", None))
        self.label_18.setText(_translate("MainWindow", "Yaw", None))
        self.label_15.setText(_translate("MainWindow", "Pitch", None))
        self.label_28.setText(_translate("MainWindow", "RPM", None))
        self.label_27.setText(_translate("MainWindow", "Velocity", None))
        self.label_41.setText(_translate("MainWindow", "Velocity", None))
        self.label_30.setText(_translate("MainWindow", "Right", None))
        self.label_29.setText(_translate("MainWindow", "Left", None))
        self.label_40.setText(_translate("MainWindow", "meters", None))
        self.label_32.setText(_translate("MainWindow", "deg", None))
        self.label_31.setText(_translate("MainWindow", "Position", None))
        self.label_42.setText(_translate("MainWindow", "m/s", None))
        self.label_36.setText(_translate("MainWindow", "%", None))
        self.label_38.setText(_translate("MainWindow", "volts", None))
        self.label_37.setText(_translate("MainWindow", "Voltage", None))
        self.label_39.setText(_translate("MainWindow", "Position", None))
        self.label_25.setText(_translate("MainWindow", "Mode", None))
        self.label_49.setText(_translate("MainWindow", "---", None))
        self.actionChange_Output_Directory.setText(_translate("MainWindow", "Change Output Directory", None))

import images_rc
